# Generated by Django 3.2.4 on 2023-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplodeitemsdb',
            name='img',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
