# Generated by Django 3.2.4 on 2023-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayproduct', '0002_uplodeitemsdb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplodeitemsdb',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
